### ISSUE TITLE
Memory consumption on k2.rnnt_loss_smoothed?

### ISSUE THREAD

**Issue by jesus-villalba** [csukuangfj/transducer-loss-benchmarking#16]
Hi,
In the k2's pruned loss, it seems that only the rnnt_loss_pruned function is benchmarked here:
https://github.com/csukuangfj/transducer-loss-benchmarking/blob/8373897fd86a64425baa198247cde439f10b1bd2/benchmark_k2_pruned.py#L141
But not the functions used to select the ranges. Have you considered the memory required by rnnt_loss_smoothed?
Thanks

**Comment by csukuangfj** [comment]
Everything between
https://github.com/csukuangfj/transducer-loss-benchmarking/blob/8373897fd86a64425baa198247cde439f10b1bd2/benchmark_k2_pruned.py#L88
and
https://github.com/csukuangfj/transducer-loss-benchmarking/blob/8373897fd86a64425baa198247cde439f10b1bd2/benchmark_k2_pruned.py#L158
is benchmarked
