### ISSUE TITLE
Inclusion of WarpRNNT - Numba

### ISSUE THREAD

**Issue by titu1994** [csukuangfj/transducer-loss-benchmarking#3]
Was wondering - since WarpRNNT itself is being tested, would you perform a benchmark comparison against https://github.com/titu1994/warprnnt_numba - which is pretty much the same as WarpRNNT but written in pure python + numba JIT compile without external compilation steps. It also has a few other features such as fastemit + gradient clamping.

I'd submit a PR myself, but I don't have access to a personal ubuntu machine to compile the current codebase dependencies.

**Comment by csukuangfj** [comment]
Thanks! That's a cool project. I will also include it in the benchmarking.
